// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Beenden() {
  return window['go']['main']['App']['Beenden']();
}

export function Daemon() {
  return window['go']['main']['App']['Daemon']();
}

export function Env() {
  return window['go']['main']['App']['Env']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}
