// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Daemon():Promise<main.DaemonInfo>;

export function Env():Promise<main.Env>;

export function OpenURL(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;
