/* Generated by tools/icons/build.py. Do not edit by hand: change the script
   and run it again. */

export const ICON_PACKS = ["tabler", "phosphor", "lucide", "pixel"] as const;
export type IconPack = (typeof ICON_PACKS)[number];
export const DEFAULT_ICON_PACK: IconPack = "tabler";

/* A pack's name is a name, the same in every language. */
export const PACK_LABELS: Record<IconPack, string> = {
  tabler: "Tabler",
  phosphor: "Phosphor",
  lucide: "Lucide",
  pixel: "Pixel",
};

/* Changes whenever a sprite does, so a window never draws from a copy the
   web view kept from before an update. */
export const SPRITE_VERSIONS: Record<IconPack, string> = {
  tabler: "0f6f81dfe7fc",
  phosphor: "828eb3d68b60",
  lucide: "22b9e0aba113",
  pixel: "d9dbd1b06115",
};

export const ICON_NAMES = [
  "overview",
  "inbox",
  "folder",
  "changes",
  "review",
  "search",
  "ports",
  "usage",
  "archive",
  "notes",
  "settings",
  "terminal",
  "file",
  "close",
  "chevron-right",
  "chevron-down",
  "play",
  "pause",
  "stop",
  "warning",
  "check",
  "git-branch",
  "diff",
  "help",
  "reset",
  "plus",
  "preview",
  "file-code",
  "file-ts",
  "file-tsx",
  "file-js",
  "file-jsx",
  "file-go",
  "file-py",
  "file-rs",
  "file-php",
  "file-shell",
  "file-css",
  "file-html",
  "file-json",
  "file-config",
  "file-env",
  "file-sql",
  "file-csv",
  "file-markdown",
  "file-text",
  "file-png",
  "file-jpg",
  "file-svg",
  "file-image",
  "file-zip",
  "file-archive",
  "file-lock",
  "file-manifest",
  "file-build",
  "file-readme",
] as const;
export type IconName = (typeof ICON_NAMES)[number];

export interface ThirdPartySet {
  id: string;
  title: string;
  repo: string;
  commit: string;
  licence: string;
  licenceFile: string;
  uses: { pack: IconPack; part: "icons" | "files" }[];
}

export const THIRD_PARTY: ThirdPartySet[] = [
  {
    id: "tabler-icons",
    title: "Tabler Icons",
    repo: "https://github.com/tabler/tabler-icons",
    commit: "55f87a73f45cf1d9eaf16d7da705065483a9e4f9",
    licence: "MIT", // german-ok: the licence's name
    licenceFile: "licenses/tabler-icons.txt",
    uses: [{ pack: "tabler", part: "files" }, { pack: "tabler", part: "icons" }],
  },
  {
    id: "phosphor-core",
    title: "Phosphor Icons",
    repo: "https://github.com/phosphor-icons/core",
    commit: "2b75f3ad12b420c9504ef05df8d2564a28f8500e",
    licence: "MIT", // german-ok: the licence's name
    licenceFile: "licenses/phosphor-core.txt",
    uses: [{ pack: "phosphor", part: "files" }, { pack: "phosphor", part: "icons" }],
  },
  {
    id: "seti-ui",
    title: "Seti UI",
    repo: "https://github.com/jesseweed/seti-ui",
    commit: "2d6c5e68b4ded73c92dac291845ee44e1182d511",
    licence: "MIT", // german-ok: the licence's name
    licenceFile: "licenses/seti-ui.txt",
    uses: [{ pack: "phosphor", part: "files" }],
  },
  {
    id: "lucide",
    title: "Lucide",
    repo: "https://github.com/lucide-icons/lucide",
    commit: "a79b2d131dab2bf20cb224bd0937b439a9c4fa99",
    licence: "ISC, MIT", // german-ok: the licence's name
    licenceFile: "licenses/lucide.txt",
    uses: [{ pack: "lucide", part: "files" }, { pack: "lucide", part: "icons" }],
  },
  {
    id: "catppuccin-vscode-icons",
    title: "Catppuccin VSCode Icons",
    repo: "https://github.com/catppuccin/vscode-icons",
    commit: "b6915da9f6889b683a110aa747de96c2820a537d",
    licence: "MIT", // german-ok: the licence's name
    licenceFile: "licenses/catppuccin-vscode-icons.txt",
    uses: [{ pack: "lucide", part: "files" }],
  },
  {
    id: "pixelarticons",
    title: "Pixelarticons",
    repo: "https://github.com/halfmage/pixelarticons",
    commit: "8275e0af7c16aa40c54ea2b90b7af83b1fe4eb4c",
    licence: "MIT", // german-ok: the licence's name
    licenceFile: "licenses/pixelarticons.txt",
    uses: [{ pack: "pixel", part: "files" }, { pack: "pixel", part: "icons" }],
  },
];

/* Icons no set had, drawn for plxr in the style of the pack they sit in. */
export const DRAWN_FOR_PLXR: { pack: IconPack; names: IconName[] }[] = [
  { pack: "pixel", names: ["diff", "ports"] },
];
